### PR TITLE
oauth target page for innogy smarthome and brands created

### PR DESCRIPTION
**Pull request by ollie-dev**
There must be separate URLs for all three brands of innogy SmartHome as
this is what innogy demands.

This PR is in context with https://github.com/openhab/openhab2-addons/pull/3227, the initial contribution of the new innogy smarthome binding.

Signed-off-by: Oliver Kuhl oliver.kuhl@gmail.com (github: ollie-dev)

### CODE REVIEW

**Comment by ollie-dev** [comment]
Yes, makes sense. See latest push.

**Comment by htreu** [comment]
Alright, thanks.
Next idea: I noticed that style.css, script.js and the fonts are identical for all three pages. Maybe we can have `aouth/innogy/css`, `aouth/innogy/js` and `aouth/innogy/fonts` folders with the files only present once. And then `aouth/innogy/innogy-smarthome.html`, `aouth/innogy/smarthome-austria.html` and `aouth/innogy/start-smarthome.html` files all referencing these files.
This would again reduce the file count and make refactoring much more simple when JavaScript needs to be adopted. wdyt?

**Comment by htreu** [comment]
@ollie-dev friendly ping. Can you provide an update with the assets merged to separate folders?

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
