### PR TITLE
Convert to Jekyll Website.

### PR DESCRIPTION
**Pull request by reitermarkus**
Signed-off-by: Markus Reiter <me@reitermark.us>

### CODE REVIEW

**Comment by reitermarkus** [comment]
I converted the website to use the Jekyll generator. This should make it easier to update in the future.

**Comment by kaikreuzer** [comment]
Markus, This is really gorgeous, thank you very much for all your work!
It fits nicely into the fact that I plan to use Jekyll for openHAB 2 documentation and want to directly feed this into the website - so your preparations are really helpful for this!

Just one very small question: I noticed that through this change the table on features/supported-technologies.html is not sortable anymore when clicking on the header. I guess this is simply not possible with markdown; do you have any idea how this feature could nonetheless be kept (a couple of users had asked for it)?

Cheers,
Kai

**Comment by reitermarkus** [comment]
Kai, I think I broke the table-sorting by using a CDN version of jQuery and upgrading it to a later version.

I'll have a look at it.

**Comment by reitermarkus** [comment]
Ok, it should be working now. Please check.

**Comment by teichsta** [comment]
Thanks a lot @reitermarkus also from my side! Much appreciated!

**Comment by kaikreuzer** [comment]
Thanks, Markus, table sorting works like a charm now. I did a small correction on the IFTTT page (https://github.com/openhab/openhab.github.io/commit/4366101ac42bddb694b5bd951c0609c60915f2f0) and merged the PR.
There is just one problem left that I couldn't figure out what has changed there: On the footer, the links to the impress and privacy policy are orange on orange - i.e. invisible. The have "inversedlink" as css class, is this something you have changed in any way?

**Comment by reitermarkus** [comment]
Yes, I think I deleted the `inverseLink` class from the CSS file and had it working with white text. I'll remove the class from HTML as well and add another selector to the CSS file.

**Pull request merged**
